
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = 'E752468D0A3EA7D86C7564B1CB6D8A5D'
    
_lr_action_items = {'TERMINAL':([2,6,9,],[6,6,6,]),'LHS':([0,1,2,6,7,8,9,10,11,],[2,2,-7,-7,-3,-6,-7,-5,-4,]),'NONTERMINAL':([2,6,9,],[9,9,9,]),'$end':([0,1,2,3,4,5,6,7,8,9,10,11,],[-7,-7,-7,-2,0,-1,-7,-3,-6,-7,-5,-4,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'Production':([0,1,],[1,1,]),'RightHand':([2,6,9,],[7,10,11,]),'empty':([0,1,2,6,9,],[3,3,8,8,8,]),'ProductionList':([0,1,],[4,5,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> ProductionList","S'",1,None,None,None),
  ('ProductionList -> Production ProductionList','ProductionList',2,'p_grammar','basicGrammarParser.py',5),
  ('ProductionList -> empty','ProductionList',1,'p_grammar','basicGrammarParser.py',6),
  ('Production -> LHS RightHand','Production',2,'p_grammar','basicGrammarParser.py',7),
  ('RightHand -> NONTERMINAL RightHand','RightHand',2,'p_grammar','basicGrammarParser.py',8),
  ('RightHand -> TERMINAL RightHand','RightHand',2,'p_grammar','basicGrammarParser.py',9),
  ('RightHand -> empty','RightHand',1,'p_grammar','basicGrammarParser.py',10),
  ('empty -> <empty>','empty',0,'p_empty','basicGrammarParser.py',13),
]
